UI/86c0w8m5z/added props to notiflication
fe-aug-24-team-1/frontend pull request #11
Opened 2024-11-06 10:15 UTC by Sukulynt

added props to notiflication so we can use it in other components by passing where we need to see notiflication and what it need to be (success/warning/error)

2024-11-06 17:06 UTC, EustasTheMonk approved these changes
Looks good! Talking about future, i think we need to choose and set some defauls values for duration and position

2024-11-07 05:54 UTC, RostyslavSharuiev requested changes

2024-11-07 05:54 UTC, RostyslavSharuiev commented on src/components/Notiflication/Notiflication.tsx
> +    if (type === 'success') {
rewrite with switch-case operator (we have static options to choose)

2024-11-08 15:01 UTC, RostyslavSharuiev approved these changes

2024-11-11 13:22 UTC, Sholudyvyy approved these changes

2024-11-12 19:07 UTC, closed without merging